name = "TravisBenchmarks"
uuid = "da49cf25-c6ab-4099-a3e8-dcf785d3da46"
authors = ["Ian Butterworth"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSVFiles = "5d742f6a-9f54-50ce-8119-2520741973ca"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["BenchmarkTools", "CSVFiles", "FileIO", "Test"]
